### ISSUE TITLE
[Bug]: vs CPUモードでCPUが先攻のとき、スタートより先にCPUの石が落ちてくる

### ISSUE THREAD

**Issue by Fanta335** [Fanta335/Connect4-GroupH#113]
### Current Behavior

タイトルの通りです。
'Are you ready?' メッセージ表示と同時にCPUの石が落ちてきます。
<img width="1277" alt="スクリーンショット 2021-11-29 23 51 58" src="https://user-images.githubusercontent.com/64186927/143890087-9fdb01ca-b4f0-4b68-b01a-8e9fd2f83cfd.png">

### Expected Behavior

STARTボタンを押してからCPUの石が落ちてくることを想定していました。

### Anything else?

最初のCPUのアクションを、canPutStone stateと紐付ければ解消できるかもしれません。

**Comment by YuyaNakamura0139** [comment]
バグ報告ありがとうございます。
修正しておきます。
