### ISSUE TITLE
ESLint, Prettierの導入

### ISSUE THREAD

**Issue by Fanta335** [Fanta335/Connect4-GroupH#25]

**Comment by Fanta335** [comment]
ESLint導入の参考文献です
https://zenn.dev/manycicadas/books/b6f2d99b5208e9/viewer/c70a5d

**Comment by y0uk1** [comment]
Prettierを整形ツールとして使って、構文チェックはeslintで行うという設定です
https://qiita.com/awakia/items/3a05edfa135762d7952c

**Comment by Fanta335** [comment]
ESLintとPrettierを組み合わせるときに気をつけてください
https://zenn.dev/teppeis/articles/2021-02-eslint-prettier-vscode

**Comment by y0uk1** [comment]
上記２つの内容を反映している記事を見つけました
https://qiita.com/soarflat/items/06377f3b96964964a65d
