### ISSUE TITLE
[New Feature]: ゲーム画面のタイマーとPlayerTurnを左右に配置する

### ISSUE THREAD

**Issue by y0uk1** [Fanta335/Connect4-GroupH#88]
### Feature Request

- タイマー
    - Player1とPlayer2で左右に配置する
    - Fontをデジタル表示にする
- PlayerTurn
    - Player1とPlayer2で左右に配置する
    - そのターンの側のライトを光らせる

### Reason For Request

デザイン性の向上

**Comment by y0uk1** [comment]
@YuyaNakamura0139 
Container.jsに石の色を制御するplayerColor1とplayerColor2というstateを追加したので、ライトの色を石の色と同じにするのであれば、このstate使ってください。

**Comment by YuyaNakamura0139** [comment]
ありがとうございます！
ちょうど表示を二つに分ける作業終わったところなので手番表示にも反映させておきます！
